batch_size: 128
code_size: 2
data_path: Dataset/IKCO1.csv
hidden_layer_size: 32
hidden_size: 256
input_size: 5
intr_size: 3
k_days: 30
learning_rate: 0.0003
num_layers: 3
prob: 0
split:
- 0.7
- 0.15
- 0.15
timestep: 90
weight_decay: 0.001
